[PATH]
raw='/media/owilab/7759343A6EC07E1C'
processed='@format /{env[HOME]}/data/processed'
mlflow='@format /{env[HOME]}/logs/mlflow'
tensorboard='@format /{env[HOME]}/logs/tensorboard'
scada='@format /{env[HOME]}/data/raw'
[NORTHER]
fleet_leader = ["NRTC01", "NRTC03", "NRTH01", "NRTF03", "NRTJ03"]
turbine_list = ["NRTA01","NRTA02","NRTA03","NRTA04",
"NRTB01","NRTB02","NRTB03","NRTB04",
"NRTC01","NRTC02","NRTC03","NRTC04",
"NRTD01","NRTD02","NRTD03","NRTD04",
"NRTE01","NRTE02","NRTE03","NRTE04",
"NRTF01","NRTF02","NRTF03","NRTF04",
"NRTG01","NRTG02","NRTG03","NRTG04",
"NRTH01","NRTH02","NRTH03","NRTH04",
"NRTI01","NRTI02","NRTI03","NRTI04",
"NRTJ01","NRTJ02","NRTJ03","NRTJ04",
"NRTK01","NRTK02","NRTK03","NRTK04",]
sensor_direction = ['X', 'Y', 'Z']
training_start = '2023-01-01'
training_end = '2024-01-01'
[NORTHER.DESIGN_CLUSTER]
C04 = "Intermediate-Shallow"
B03 = "Intermediate-Deep"
B04 = "Deep"
B02 = "Intermediate-Deep"
A04 = "Intermediate-Deep"
D04 = "Intermediate-Shallow"
C03 = "Shallow"
D03 = "Intermediate-Shallow"
C02 = "Intermediate-Shallow"
D02 = "Intermediate-Shallow"
C01 = "Intermediate-Shallow"
B01 = "Intermediate-Shallow"
A03 = "Intermediate-Deep"
E02 = "Intermediate-Shallow"
D01 = "Intermediate-Shallow"
E01 = "Intermediate-Shallow"
K01 = "Intermediate-Shallow"
A01 = "Intermediate-Deep"
A02 = "Deep"
E03 = "Intermediate-Deep"
F01 = "Intermediate-Shallow"
H01 = "Intermediate-Shallow"
E04 = "Intermediate-Deep"
F02 = "Intermediate-Deep"
G01 = "Intermediate-Shallow"
J01 = "Shallow"
K02 = "Deep"
I01 = "Intermediate-Shallow"
K03 = "Deep"
J02 = "Shallow"
K04 = "Deep"
F04 = "Intermediate-Deep"
F03 = "Intermediate-Deep"
H02 = "Intermediate-Shallow"
I02 = "Shallow"
I03 = "Intermediate-Shallow"
J03 = "Deep"
J04 = "Shallow"
G03 = "Intermediate-Deep"
G02 = "Deep"
G04 = "Deep"
H03 = "Shallow"
H04 = "Shallow"
I04 = "Intermediate-Deep"